site_name: Endades Support
# site_favicon: img/favicon.ico

plugins:
  - search
  - i18n:
      default_language: es
      docs_structure: folder
      languages:
        - locale: es
          name: Español
          default: true
          build: true
          nav:
            - Inicio: index.md
            - Requisitos del sistema: Requisitos_Sistema.md
            - Instalador Endades Suite: Instalador_EndadesSuite.md
            - Configuración del sistema: Configuracion_Sistema.md
            - Requisitos del entorno ENBLAU: Requisitos_ENBLAU.md
            - Requisitos instalación enSITE: Requisitos_enSITE.md
            - Posibles errores: Posibles_Errores.md
        - locale: en
          name: English
          build: true
          nav:
            - Home: index.md
            - System requirements: Requisitos_Sistema.md
            - Endades Suite installer: Instalador_EndadesSuite.md
            - System configuration: Configuracion_Sistema.md
            - ENBLAU environment requirements: Requisitos_ENBLAU.md
            - enSITE installation requirements: Requisitos_enSITE.md
            - Possible errors: Posibles_Errores.md
        - locale: it
          name: Italiano
          build: true
          nav:
            - Inizio: index.md
            - Requisiti di sistema: Requisitos_Sistema.md
            - Installatore Endades Suite: Instalador_EndadesSuite.md
            - Configurazione del sistema: Configuracion_Sistema.md
            - Requisiti dell'ambiente ENBLAU: Requisitos_ENBLAU.md
            - Requisiti di installazione enSITE: Requisitos_enSITE.md
            - Possibili errori: Posibles_Errores.md
        - locale: pt
          name: Português
          build: true
          nav:
            - Início: index.md
            - Requisitos do sistema: Requisitos_Sistema.md
            - Instalador Endades Suite: Instalador_EndadesSuite.md
            - Configuração do sistema: Configuracion_Sistema.md
            - Requisitos do ambiente ENBLAU: Requisitos_ENBLAU.md
            - Requisitos de instalação enSITE: Requisitos_enSITE.md
            - Possíveis erros: Posibles_Errores.md

theme:
  name: readthedocs
  highlightjs: true
  custom_dir: overrides

### Change font style ###
extra_css:
  - stylesheets/custom.css

# extra_javascript:
#   - js/lang-switcher.js

### Hide logos and copy rights ###
extra:
  hide:
    github: true
    edit_page: true

copyright: " "